#!/usr/bin/env python3

"""

- run.py -

This file was generated by 'cinit'.

Built by Simon Danielsson
License @ EOF.

Source: https://github.com/simon-danielsson/c_template
Author: https://www.simondanielsson.se/

Requirements: Python 3.10+

"""

import subprocess, sys, os
from pathlib import Path
from datetime import datetime, timedelta
from dataclasses import dataclass
from enum import Enum
import platform

ROOT = Path(__file__).parent.resolve()
SRC_DIR = Path(f"{ROOT}/src")
TESTS_DIR = Path(f"{ROOT}/tests")
PROJ_NAME = ROOT.name  # env var
PROJ_REPO = f"https://github.com/simon-danielsson/{PROJ_NAME}"  # env var
AUTH = "Simon Danielsson"  # env var
AUTH_CONT = "contact@simondanielsson.se"  # env var
C_STD = "c99"  # c standard used to compile program

AUTO_RUN = True  # if true, run binary after compile
AUTO_RUN_ARGS = []  # program args used at auto run
PRINT_COMPILE_DETAILS = True  # build-type, compiler, compile time

C_FLAGS_DEBUG = [
        "-O0",
        "-DDEBUG",
        "-fsanitize=address",
        "-fsanitize=undefined",
        "-fno-omit-frame-pointer",
        "-Wall",
        "-Wpedantic",
        "-Wshadow",
        "-Werror=format-security",
        ]

C_FLAGS_RELEASE = ["-flto", "-O2", "-DNDEBUG"]

BLD = "\033[1m"
RST = "\x1b[0m"

# classes & types -------------------------------------------------------------

class BuildType(Enum):
    Release = "release"
    Debug = "debug"
    Test = "test"
    Install = "install"

@dataclass
class Args:
    runargs: list[str]
    build: BuildType = BuildType.Debug
    help: bool = False
    print_details: None | bool = None
    prog: str = ""
    test_n: int = 0

@dataclass
class CmdExec:
    process: subprocess.CompletedProcess[str]
    exec_time: timedelta

# cmd exec --------------------------------------------------------------------

def run_cmd(cmd) -> CmdExec:
    start = datetime.now()
    process = subprocess.run(cmd, capture_output=True, text=True)
    end = datetime.now()
    exec_time = end - start
    return CmdExec(exec_time=exec_time, process=process)

# git & env -------------------------------------------------------------------

def get_git_vers() -> str:
    cmd = ["git", "describe", "--tags", "--abbrev=0"]
    result = run_cmd(cmd)
    if result.process.returncode != 0:
        return "v0.0.0"
    return result.process.stdout.strip()

def get_git_hash(short: bool) -> str:
    cmd = ["git", "rev-parse", "HEAD"]
    if short:
        cmd.insert(2, "--short")
    result = run_cmd(cmd)
    if result.process.returncode != 0:
        return "0".zfill(7)
    return result.process.stdout.strip()

GIT_V = get_git_vers()
GIT_HASH_SH = get_git_hash(True)
GIT_HASH = get_git_hash(False)

ENV_FLAGS = [
        f'-DENV_GITHASH="{GIT_HASH}"',
        f'-DENV_GITTAG="{GIT_V}"',
        f'-DENV_NAME="{PROJ_NAME}"',
        f'-DENV_AUTHOR="{AUTH}"',
        f'-DENV_CONTACT="{AUTH_CONT}"',
        f'-DENV_REPO="{PROJ_REPO}"',
        f"-std={C_STD}",
        ]

# build -----------------------------------------------------------------------

def collect_src_files(src: Path) -> list[str]:
    return [f"{path}" for path in src.rglob("*.c")]

def build(a: Args) -> None:
    build_dir = Path(f"{ROOT}/build/{a.build.value}")
    bin_name = f"{PROJ_NAME}_{a.build.value}_{GIT_V}_{GIT_HASH_SH}"
    c_flags: list[str] = ENV_FLAGS

    match a.build:
        case BuildType.Test:
            c_flags = c_flags + C_FLAGS_DEBUG + [f"-DTEST={a.test_n}"]
        case BuildType.Debug:
            c_flags = c_flags + C_FLAGS_DEBUG
        case BuildType.Release:
            c_flags = c_flags + C_FLAGS_RELEASE
        case BuildType.Install:
            c_flags = c_flags + C_FLAGS_RELEASE
            bin_name = f"{PROJ_NAME}"

    os.makedirs(build_dir, exist_ok=True)

    build_cmd = (
            c_flags
            + collect_src_files(SRC_DIR)
            + collect_src_files(TESTS_DIR)
            + ["-o", f"{build_dir}/{bin_name}"]
            )

    try:
        compiler = "clang"
        output = run_cmd([compiler] + build_cmd)
    except FileNotFoundError:
        compiler = "gcc"
        output = run_cmd([compiler] + build_cmd)

    if a.print_details == None and PRINT_COMPILE_DETAILS:
        print(f"{a.build.value} via " f"{compiler} ({C_STD}) {output.exec_time}")
    if a.print_details == True:
        print(f"{a.build.value} via " f"{compiler} ({C_STD}) {output.exec_time}")

    if AUTO_RUN and a.build != BuildType.Install:
        if output.process.returncode != 0:
            print(output.process.stderr)
            sys.exit(output.process.returncode)

        env = os.environ.copy()
        if platform.system() == "Darwin":
            env["MallocNanoZone"] = "0"
        exe_path = (build_dir / bin_name).resolve()
        os.execvpe(str(exe_path), [str(exe_path)] + AUTO_RUN_ARGS + a.runargs, env)

# main ------------------------------------------------------------------------

def help() -> None:
    print(
            f"{BLD}run release{RST}\n"
            f"-> ./build/release\n"
            f"{BLD}run debug{RST}\n"
            f"-> ./build/debug\n"
            f"{BLD}run install{RST}\n"
            f"-> ./build/install"
            f"{BLD}run test --test=<num>{RST}\n"
            f"-> ./build/test"
            )

def get_args() -> Args:
    a: Args = Args(runargs=[])
    a.prog = sys.argv[0].rsplit("/")[-1]
    count = 0
    while count < len(sys.argv):
        arg = sys.argv[count]
        match arg:
            case d if d.startswith("--no-details"):  # --test=#
                a.print_details = False
            case t if t.startswith("--test="):  # --test=#
                a.test_n = int(arg.split("=", 1)[1])
            case runarg if runarg.startswith("--"):
                count += 1
                for ra in sys.argv[count:]:
                    a.runargs.append(ra)
            case r if r.startswith("r"):
                a.build = BuildType.Release
            case r if r.startswith("t"):
                a.build = BuildType.Test
            case d if d.startswith("d"):
                a.build = BuildType.Debug
            case i if i.startswith("i"):
                a.build = BuildType.Install
            case h if h.startswith("h"):
                a.help = True
        count += 1

    return a

def main():
    a: Args = get_args()
    if a.help:
        help()
        return
    build(a)

if __name__ == "__main__":
    main()

# Copyright © 2026 Simon Danielsson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files, to deal in the Software
# without restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies of the
# Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
